# Generated by Django 6.0.4 on 2026-04-29 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dealership", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("final_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("processing", "В обработке"),
                            ("approved", "Подтверждена"),
                            ("paid", "Оплачена"),
                            ("rejected", "Отклонена"),
                            ("canceled", "Отменена покупателем"),
                            ("failed", "Техническая ошибка"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("insufficient_funds", "Недостаточно средств"),
                            ("out_of_stock", "Нет в наличии"),
                            ("price_changed", "Цена изменилась"),
                            ("dealership_inactive", "Автосалон неактивен"),
                            ("transaction_not_approved", "Транзакция не подтверждена"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="offers", to="buyers.buyerprofile"
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="offers", to="dealership.dealership"
                    ),
                ),
                (
                    "dealership_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="dealership.dealershipinventory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
