# Generated by Django 6.0.4 on 2026-05-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyerprofile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="offer",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSUFFICIENT_FUNDS", "Insufficient funds"),
                    ("OUT_OF_STOCK", "Out of stock"),
                    ("PRICE_CHANGED", "Price changed"),
                    ("DEALERSHIP_INACTIVE", "Dealership inactive"),
                    ("TRANSACTION_NOT_APPROVED", "Transaction not approved"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROCESSING", "Processing"),
                    ("APPROVED", "Approved"),
                    ("PAID", "Paid"),
                    ("REJECTED", "Rejected"),
                    ("CANCELED", "Canceled"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
