# Generated by Django 6.0.6 on 2026-06-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0002_alter_buyerprofile_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSUFFICIENT_FUNDS", "Insufficient funds"),
                    ("OUT_OF_STOCK", "Out of stock"),
                    ("DEALERSHIP_INACTIVE", "Dealership inactive"),
                ],
                max_length=32,
            ),
        ),
    ]
