# Generated by Django 6.0.4 on 2026-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("generation", models.CharField(blank=True, max_length=100)),
                ("trim_level", models.CharField(blank=True, max_length=100)),
                (
                    "body_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedan", "Седан"),
                            ("hatchback", "Хэтчбек"),
                            ("suv", "SUV"),
                            ("coupe", "Купе"),
                            ("wagon", "Универсал"),
                            ("pickup", "Пикап"),
                            ("van", "Минивэн"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "Бензин"),
                            ("diesel", "Дизель"),
                            ("hybrid", "Гибрид"),
                            ("electric", "Электро"),
                            ("gas", "Газ"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Механика"),
                            ("automatic", "Автомат"),
                            ("robot", "Робот"),
                            ("cvt", "Вариатор"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        blank=True, choices=[("fwd", "Передний"), ("rwd", "Задний"), ("awd", "Полный")], max_length=10
                    ),
                ),
                ("engine_volume", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("horsepower", models.PositiveIntegerField(blank=True, null=True)),
                ("seat_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("door_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("production_year_from", models.PositiveIntegerField(blank=True, null=True)),
                ("production_year_to", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [models.Index(fields=["brand", "model_name"], name="cars_carmod_brand_a61728_idx")],
            },
        ),
    ]
