# Generated by Django 6.0.5 on 2026-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="drive_type",
            field=models.CharField(
                blank=True,
                choices=[("fwd", "Front-wheel drive"), ("rwd", "Rear-wheel drive"), ("awd", "All-wheel drive")],
                max_length=10,
            ),
        ),
    ]
