# Generated by Django 6.0.5 on 2026-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0002_alter_carmodel_drive_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SEDAN", "Sedan"),
                    ("HATCHBACK", "Hatchback"),
                    ("SUV", "SUV"),
                    ("COUPE", "Coupe"),
                    ("WAGON", "Station Wagon"),
                    ("PICKUP", "Pickup"),
                    ("VAN", "Minivan"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="drive_type",
            field=models.CharField(
                blank=True,
                choices=[("FWD", "Front-wheel drive"), ("RWD", "Rear-wheel drive"), ("AWD", "All-wheel drive")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PETROL", "Petrol"),
                    ("DIESEL", "Diesel"),
                    ("HYBRID", "Hybrid"),
                    ("ELECTRIC", "Electric"),
                    ("GAS", "Gas"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANUAL", "Manual"),
                    ("AUTOMATIC", "Automatic"),
                    ("ROBOT", "Automated Manual"),
                    ("CVT", "CVT"),
                ],
                max_length=20,
            ),
        ),
    ]
