# Generated by Django 6.0.4 on 2026-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Покупатель"),
                    ("supplier", "Поставщик"),
                    ("dealership", "Автосалон"),
                    ("worker_supplier", "Сотрудник поставщика"),
                    ("worker_dealership", "Сотрудник автосалона"),
                    ("admin", "админ"),
                ],
                default="admin",
                max_length=32,
            ),
        ),
    ]
