# Generated by Django 6.0.4 on 2026-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("BUYER", "Buyer"),
                    ("WORKER_SUPPLIER", "Suppliers worker"),
                    ("WORKER_DEALERSHIP", "Dealerships worker"),
                    ("NOBODY", "Nobody"),
                    ("ADMIN", "Admin"),
                ],
                default="NOBODY",
                max_length=32,
            ),
        ),
    ]
