# Generated by Django 6.0.4 on 2026-04-27 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("founded_year", models.IntegerField()),
                ("contact_phone", models.CharField(max_length=30)),
                ("contact_email", models.EmailField(max_length=254)),
                ("status", models.CharField(max_length=50)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
