# Generated by Django 6.0.4 on 2026-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0002_supplier_is_active_alter_supplier_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="status",
        ),
        migrations.AlterField(
            model_name="supplier",
            name="founded_year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workerprofilesupplier",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workerprofilesupplier",
            name="position",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("MANAGER", "Manager"), ("SALES", "Sales")], max_length=50
            ),
        ),
    ]
