# Generated by Django 6.0.5 on 2026-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0003_remove_supplier_owner_remove_supplier_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierpromotion",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active"), ("expired", "Expired"), ("canceled", "Canceled")],
                default="draft",
                max_length=20,
            ),
        ),
    ]
