# Generated by Django 6.0.5 on 2026-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0004_alter_supplierpromotion_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierpromotion",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("EXPIRED", "Expired"), ("CANCELED", "Canceled")],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
