[pytest]
DJANGO_SETTINGS_MODULE = car_service.test_settings
python_files = test_*.py tests.py
python_classes = Test* *Test *TestCase
python_functions = test_*
# --create-db
addopts = -v --reuse-db --tb=short
markers =
    api: API layer tests
    service: business logic tests
    celery: Celery scenarios