# Generated by Django 6.0.7 on 2026-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("EXPIRED", "Expired")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
