# Generated by Django 6.0.4 on 2026-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealership", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealership",
            name="status",
        ),
        migrations.RemoveField(
            model_name="dealership",
            name="user",
        ),
        migrations.AlterField(
            model_name="dealership",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workerprofiledealership",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workerprofiledealership",
            name="position",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("MANAGER", "Manager"), ("SALES", "Sales")], max_length=50
            ),
        ),
    ]
