# Generated by Django 6.0.5 on 2026-06-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_alter_carmodel_body_type_alter_carmodel_drive_type_and_more"),
        ("dealership", "0002_remove_dealership_status_remove_dealership_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dealershipinventory",
            unique_together={("dealership", "car_model")},
        ),
        migrations.CreateModel(
            name="DealershipPreferredCar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        default=3, help_text="The minimum inventory the dealership wants to maintain"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferred_by_dealerships",
                        to="cars.carmodel",
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_cars",
                        to="dealership.dealership",
                    ),
                ),
            ],
            options={
                "unique_together": {("dealership", "car_model")},
            },
        ),
    ]
