# Generated by Django 6.0.5 on 2026-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealership", "0003_alter_dealershipinventory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealershippromotion",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "draft"), ("ACTIVE", "active"), ("EXPIRED", "expired"), ("CANCELED", "canceled")],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
