# Generated by Django 6.0.5 on 2026-06-09 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cars", "0003_alter_carmodel_body_type_alter_carmodel_drive_type_and_more"),
        ("dealership", "0004_alter_dealershippromotion_status"),
        ("suppliers", "0005_alter_supplierpromotion_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPurchaseLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PURCHASED", "Purchased"),
                            ("SKIPPED_NO_OFFER", "No supplier offer found"),
                            ("SKIPPED_NO_FUNDS", "Insufficient dealership balance"),
                            ("FAILED", "Failed with error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("quantity_requested", models.PositiveIntegerField(default=0)),
                ("quantity_purchased", models.PositiveIntegerField(default=0)),
                ("unit_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("message", models.TextField(blank=True)),
                ("tick_id", models.CharField(db_index=True, max_length=64)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_purchase_logs",
                        to="cars.carmodel",
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_purchase_logs",
                        to="dealership.dealership",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_purchase_logs",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["dealership", "-created_at"], name="purchases_a_dealers_1b9ece_idx"),
                    models.Index(fields=["tick_id"], name="purchases_a_tick_id_09ba1e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierPurchaseTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("discount_percent_applied", models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_transactions",
                        to="cars.carmodel",
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_transactions",
                        to="dealership.dealership",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_transactions",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "supplier_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_transactions",
                        to="suppliers.supplierinventory",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["dealership", "-created_at"], name="purchases_s_dealers_ac2d97_idx"),
                    models.Index(fields=["supplier", "-created_at"], name="purchases_s_supplie_e24f9d_idx"),
                ],
            },
        ),
    ]
