# Generated by Django 6.0.6 on 2026-06-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_alter_carmodel_body_type_alter_carmodel_drive_type_and_more"),
        ("dealership", "0004_alter_dealershippromotion_status"),
        ("purchases", "0001_initial"),
        ("suppliers", "0005_alter_supplierpromotion_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SupplierPurchaseTransaction",
            new_name="DealershipPurchaseTransaction",
        ),
        migrations.RenameIndex(
            model_name="dealershippurchasetransaction",
            new_name="purchases_d_dealers_a7f9fe_idx",
            old_name="purchases_s_dealers_ac2d97_idx",
        ),
        migrations.RenameIndex(
            model_name="dealershippurchasetransaction",
            new_name="purchases_d_supplie_93815b_idx",
            old_name="purchases_s_supplie_e24f9d_idx",
        ),
        migrations.AlterField(
            model_name="autopurchaselog",
            name="car_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_purchase_logs",
                to="cars.carmodel",
            ),
        ),
        migrations.AlterField(
            model_name="autopurchaselog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("PENDING", "In progress"),
                    ("PURCHASED", "Purchased"),
                    ("SKIPPED_NO_OFFER", "No supplier offer found"),
                    ("SKIPPED_NO_FUNDS", "Insufficient dealership balance"),
                    ("FAILED", "Failed with error"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="autopurchaselog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("car_model__isnull", True)),
                fields=("dealership", "tick_id"),
                name="unique_sentinel_per_tick",
            ),
        ),
    ]
